# Welcome to Jekyll!
#
# If you change something here, please rerun `jekyll serve`

# Site settings
title: ACHILLES 0x01
description: Write-ups | Hacking & Coding.
baseurl: "" # put subpath of your site, e.g. /blog
url: "https://achilles0x01.github.io" # put the base hostname & protocol for your site

google_analytics: UA-124258141-2

email: achilles0x0@pm.me
github_username:  Achilles0x01

paginate: 5
permalink: /:title/

gems: [jekyll-paginate, kramdown]
markdown: kramdown
